[project]
name = "secure-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cryptography==42.0.2",
    "streamlit==1.32.0",
]
